print("=== Chatbot Architecture Flow ===")
print("1. User Input -> 'Who won the IPL?'")
print("       |")
print("       v")
print("2. LangChain Processing (Memory & Prompt Formatting)")
print("       |")
print("       v")
print("3. LLM Request -> Groq API (Llama Model)")
print("       |")
print("       v")
print("4. LLM Response -> 'Chennai Super Kings won!'")
print("       |")
print("       v")
print("5. Terminal Display -> Show to User")
